In [ ]:
import numpy as np

In [ ]:
np.array([1,2,3])

array([1, 2, 3])

In [ ]:
a=np.zeros((2,3))

In [ ]:
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.arange(0,12,2)

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
np.linspace(0,1,4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [ ]:
mean=10
stdev=3
number_values=20
np.random.normal(mean,stdev,number_values)

array([ 5.58208546, 11.25817755, 14.05581097, 11.85367404,  7.52394995,
       10.01038397,  8.51503111,  9.83691386,  9.23912275,  8.6076193 ,
        5.2771408 ,  7.38438487,  7.98802731, 11.50364761, 10.5570012 ,
       12.34675873, 11.51738451,  9.14388637,  2.99212486, 12.3383602 ])

In [ ]:
x=np.arange(6).reshape(2,3)

In [ ]:
x

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
x[1:3]

array([[3, 4, 5]])

In [ ]:
x[:3]

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
x+10

array([[10, 11, 12],
       [13, 14, 15]])

In [ ]:
listnum=[1,2,3,34,5,6]

In [ ]:
type(listnum)

list

In [ ]:
xx=np.array(listnum)

In [ ]:
type(xx)

numpy.ndarray

# IntroductionToPandas

In [1]:
import pandas as pd

In [ ]:
from google.colab import files

In [ ]:
newupload=files.upload()

In [ ]:
url='https://gist.githubusercontent.com/llagerlof/928847ece919d8549112/raw/a36e7bb9c7a16342af7b46e1bc2f4f6e3b01290d/people.csv'

In [ ]:
df1=pd.read_csv(url)

In [ ]:
df1

In [ ]:
import io

In [ ]:
newupload1=files.upload()

In [ ]:
df2=pd.read_csv(io.BytesIO(newupload1['diabetes_data.csv']))

In [ ]:
df2

In [ ]:
df2.head(15)

In [ ]:
animals=['tiger','cat','dog','monkey','gorrila']

In [ ]:
df3=pd.Series(animals)

In [ ]:
type(df3)

In [ ]:
numbers=[1,2,3,4,None]

In [ ]:
xx=pd.Series(numbers)

In [ ]:
xx

In [ ]:
np.nan==None

In [ ]:
np.nan=np.nan

In [ ]:
np.isnan(6)

In [ ]:
np.isnan(np.nan)

In [ ]:
animalswithIndex=pd.Series(['tiger','cat','dog'], index=['India','Nepal','France'])

In [ ]:
animalswithIndex.index

In [ ]:
animalswithIndex

In [ ]:
animalswithIndex.iloc[2]

In [ ]:
animalswithIndex.loc['India']

In [ ]:
df4=pd.DataFrame([{'Name':'Rahul','Roll No':'19bec001'},
                  {'Name':'Rohit','Roll No':'19bec002'},
                  {'Name':'Aaradhaya','Roll No':'19bec003'},
                  {'Name':'Navya','Roll No':'19bec004'}])

In [ ]:
df4

In [ ]:
df4['Roll No']

In [ ]:
df4['CGPA']=[8.3,9.5,6.5,8.8]

In [ ]:
df4

In [ ]:
df5=pd.DataFrame([{'Name':'asdf','Roll No':'19bec001'},
                  {'Name':'try','Roll No':'19bec002'},
                  {'Name':'fjh','Roll No':'19bec003'},
                  {'Name':'vbvb','Roll No':'19bec004'}])

In [ ]:
df5['CGPA']=[7.3,7.5,7.5,7.8]

In [ ]:
df5

In [ ]:
pd.merge(df4,df5,how='outer',left_index=True,right_index=True)

In [ ]:
pd.merge(df4,df5,how='right',left_index=True,right_index=True)

# Fetching webpage Contents using requests

In [ ]:
import requests

In [ ]:
import bs4

In [ ]:
import lxml.etree as xml


In [ ]:
URL = "https://github.com/requests/requests"

In [ ]:
requests.get(URL)

<Response [200]>

In [ ]:
git_webpage=bs4.BeautifulSoup(requests.get(URL,{}).text,"lxml")

In [ ]:
git_webpage

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<link href="https://github.githubassets.com" rel="dns-prefetch"/>
<link href="https://avatars.githubusercontent.com" rel="dns-prefetch"/>
<link href="https://github-cloud.s3.amazonaws.com" rel="dns-prefetch"/>
<link href="https://user-images.githubusercontent.com/" rel="dns-prefetch"/>
<link crossorigin="anonymous" href="https://github.githubassets.com/assets/frameworks-93d34cfdadb1618eb00917161bb7f744.css" integrity="sha512-k9NM/a2xYY6wCRcWG7f3ROm4X5CJNikViGX0N8YIxs6sUYAe/j08/RSHXr3fA9wLIy87AMFCgXm6jbvhZhIXWw==" media="all" rel="stylesheet"/>
<link crossorigin="anonymous" href="https://github.githubassets.com/assets/site-6547fa2bebd0a8c63e461573691982cb.css" integrity="sha512-ZUf6K+vQqMY+RhVzaRmCy2ePbSZad4TkaGRbd6v5gFt6f9Q/nqjDkBDjQgXNmZw7J9mcYxlsE4fhRw7CTluRow==" media="all" rel="stylesheet"/>
<link crossorigin="anonymous" href="https://github.githubassets.com/assets/behaviors-9a6d928a0cc4b9d03dc52f27ca22afa4.css" integr

In [ ]:
git_webpage.head.title

<title>GitHub - psf/requests: A simple, yet elegant HTTP library.</title>

In [ ]:
git_webpage.head.title.text

'GitHub - psf/requests: A simple, yet elegant HTTP library.'

In [ ]:
git_webpage.body

<body class="logged-out env-production page-responsive">
<div class="position-relative js-header-wrapper ">
<a class="px-2 py-4 bg-blue text-white show-on-focus js-skip-to-content" href="#start-of-content">Skip to content</a>
<span class="progress-pjax-loader width-full js-pjax-loader-bar Progress position-fixed">
<span class="Progress-item progress-pjax-loader-bar " style="background-color: #79b8ff;width: 0%;"></span>
</span>
<header class="Header-old header-logged-out js-details-container Details position-relative f4 py-2" role="banner">
<div class="container-xl d-lg-flex flex-items-center p-responsive">
<div class="d-flex flex-justify-between flex-items-center">
<a aria-label="Homepage" class="mr-4" data-ga-click="(Logged out) Header, go to homepage, icon:logo-wordmark" href="https://github.com/">
<svg aria-hidden="true" class="octicon octicon-mark-github text-white" height="32" version="1.1" viewbox="0 0 16 16" width="32"><path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4

In [ ]:
tags_elements=git_webpage.find(name="div", attrs={"class":"BorderGrid-cell"})

In [ ]:
tags_elements

<div class="BorderGrid-cell">
<h2 class="mb-3 h4">About</h2>
<p class="f4 mt-3">
      A simple, yet elegant HTTP library.
    </p>
<div class="mt-3 d-flex flex-items-center">
<svg aria-hidden="true" class="octicon octicon-link flex-shrink-0 mr-2" height="16" version="1.1" viewbox="0 0 16 16" width="16"><path d="M7.775 3.275a.75.75 0 001.06 1.06l1.25-1.25a2 2 0 112.83 2.83l-2.5 2.5a2 2 0 01-2.83 0 .75.75 0 00-1.06 1.06 3.5 3.5 0 004.95 0l2.5-2.5a3.5 3.5 0 00-4.95-4.95l-1.25 1.25zm-4.69 9.64a2 2 0 010-2.83l2.5-2.5a2 2 0 012.83 0 .75.75 0 001.06-1.06 3.5 3.5 0 00-4.95 0l-2.5 2.5a3.5 3.5 0 004.95 4.95l1.25-1.25a.75.75 0 00-1.06-1.06l-1.25 1.25a2 2 0 01-2.83 0z" fill-rule="evenodd"></path></svg>
<span class="flex-auto min-width-0 css-truncate css-truncate-target width-fit">
<a class="text-bold" href="https://requests.readthedocs.io" rel="noopener noreferrer" role="link" target="_blank" title="https://requests.readthedocs.io">requests.readthedocs.io</a>
</span>
</div>
<h3 class="sr-only">To

In [ ]:
url='https://www.imdb.com/search/title/?release_date=2017&sort=num_votes,desc&page=1'

In [ ]:
response=requests.get(url)

In [ ]:
response.text[:500]

'\n\n<!DOCTYPE html>\n<html\n    xmlns:og="http://ogp.me/ns#"\n    xmlns:fb="http://www.facebook.com/2008/fbml">\n    <head>\n         \n        <meta charset="utf-8">\n        <meta http-equiv="X-UA-Compatible" content="IE=edge">\n\n    <meta name="apple-itunes-app" content="app-id=342792525, app-argument=imdb:///?src=mdot">\n\n\n\n        <script type="text/javascript">var IMDbTimer={starttime: new Date().getTime(),pt:\'java\'};</script>\n\n<script>\n    if (typeof uet == \'function\') {\n      uet("bb", "LoadTitle",'

In [ ]:
from bs4 import BeautifulSoup
html_soup=BeautifulSoup(response.text,'html.parser')

In [ ]:
html_soup


<!DOCTYPE html>

<html xmlns:fb="http://www.facebook.com/2008/fbml" xmlns:og="http://ogp.me/ns#">
<head>
<meta charset="utf-8"/>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
<meta content="app-id=342792525, app-argument=imdb:///?src=mdot" name="apple-itunes-app"/>
<script type="text/javascript">var IMDbTimer={starttime: new Date().getTime(),pt:'java'};</script>
<script>
    if (typeof uet == 'function') {
      uet("bb", "LoadTitle", {wb: 1});
    }
</script>
<script>(function(t){ (t.events = t.events || {})["csm_head_pre_title"] = new Date().getTime(); })(IMDbTimer);</script>
<title>Released between 2017-01-01 and 2017-12-31
(Sorted by Number of Votes Descending) - IMDb</title>
<script>(function(t){ (t.events = t.events || {})["csm_head_post_title"] = new Date().getTime(); })(IMDbTimer);</script>
<script>
    if (typeof uet == 'function') {
      uet("be", "LoadTitle", {wb: 1});
    }
</script>
<script>
    if (typeof uex == 'function') {
      uex("ld", "LoadTitle", {wb: 1

In [ ]:
movie_containers=html_soup.find_all('div',class_='lister-item mode-advanced')

In [ ]:
names=[]
years=[]
imbd_ratings=[]
metascores=[]
votes=[]

for container in movie_containers:
  if container.find('div',class_='ratings-metascore') is not None:
    name=container.h3.a.text
    names.append(name)

    m_score=container.find('span', class_='metascore').text
    metascores.append(int(m_score))

    year=container.h3.find('span', class_='lister-item-year').text
    years.append(year)

    vote=container.find('span', attrs={'name':'nv'})['data-value']
    votes.append(int(vote))





In [ ]:
df6=pd.DataFrame({'movie':names,
                 'year':years,
                 'metascore':metascores,
                 'votes':votes})

In [ ]:
df6

movie  ...   votes
0                                              Logan  ...  647279
1                                     Thor: Ragnarok  ...  587100
2                     Guardians of the Galaxy Vol. 2  ...  569395
3                                       Wonder Woman  ...  567692
4            Star Wars: Episode VIII - The Last Jedi  ...  564624
5                                            Dunkirk  ...  554491
6                             Spider-Man: Homecoming  ...  512404
7                                            Get Out  ...  492276
8                                  Blade Runner 2049  ...  461161
9                                                 It  ...  459285
10                                       Baby Driver  ...  438747
11         Three Billboards Outside Ebbing, Missouri  ...  431833
12                                    Justice League  ...  384539
13                                              Coco  ...  383219
14                                The Shape of Water  ...  370675
15                              John Wick: Chapter 2  ...  366057
16                    Jumanji: Welcome to the Jungle  ...  319584
17                              Beauty and the Beast  ...  274280
18                       Kingsman: The Golden Circle  ...  272934
19                                Kong: Skull Island  ...  268854
20  Pirates of the Caribbean: Dead Men Tell No Tales  ...  263417
21                                   Alien: Covenant  ...  254085
22                                         Lady Bird  ...  241174
23                              The Greatest Showman  ...  238824
24                    War for the Planet of the Apes  ...  227699
25                      Murder on the Orient Express  ...  213309
26                              Call Me by Your Name  ...  212222
27                                              Life  ...  207183
28                                        Wind River  ...  205008
29                           The Fate of the Furious  ...  204653
30                                Ghost in the Shell  ...  196064
31                  King Arthur: Legend of the Sword  ...  191808
32                                           Mother!  ...  191257
33                            The Hitman's Bodyguard  ...  186733
34                                          I, Tonya  ...  181852
35                                     Atomic Blonde  ...  175871
36                                         The Mummy  ...  172875
37                                      Darkest Hour  ...  172052
38                                            Bright  ...  168700
39       Valerian and the City of a Thousand Planets  ...  162127
40                                          Baywatch  ...  161029
41                                     American Made  ...  158467

[42 rows x 4 columns]