In [ ]:
import numpy as np


In [ ]:
true=np.array([1,1,0,0,1]) # Ground truth
pred=np.array([1,1,1,1,0])

In [ ]:
def accuracy(true,pred):
  true=true.flatten()
  pred=pred.flatten()
  correct=(true==pred).sum()
  return correct/len(pred)



In [ ]:
accuracy(true,pred)

0.4

In [ ]:
def precision(true, pred):
  true=true.flatten()
  pred=pred.flatten()
  prec=(true*pred).sum()/pred.sum()
  return prec


In [ ]:
precision(true,pred)

0.5

In [ ]:
def recall(true,pred):
  true=true.flatten()
  pred=pred.flatten()
  reca=(true*pred).sum()/true.sum()
  return reca

In [ ]:
recall(true,pred)

0.6666666666666666

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
confusion_matrix(true,pred)

array([[0, 2],
       [1, 2]])

In [ ]:
def fScore(true,pred):
  P=precision(true,pred)
  R=recall(true,pred)
  return (2*P*R)/(P+R)
  

In [ ]:
fScore(true,pred)

0.5714285714285715

In [ ]:
#Metthew's Correlation Coefficient

In [ ]:
import math

In [ ]:
def MCC(true,pred):
  true=true.flatten()
  pred=pred.flatten()
  tp=(true*pred).sum()
  tn=0 #assignment
  fp=0 #assignment
  fn=0 #assignment
  mcc=(tp*tn-fp*fn)/math.sqrt((tp+fp)*(tp+fn)*(tn+fp)*(tn+fn))
  return mcc
  

In [ ]:
true1=np.array([1,2.2,3])
pred1=np.array([0,2.2,7])

In [ ]:
def mean_abs_error(true,pred):
  return abs(true-pred).mean()

In [ ]:
mean_abs_error(true1,pred1)

1.6666666666666667

In [ ]:
def mean_sq_err(true,pred):
  true=true.flatten()
  pred=pred.flatten()
  temp=true-pred
  x=((temp**2).sum())/len(temp)
  return x
  

In [ ]:
mean_sq_err(true1,pred1)

5.666666666666667

In [ ]:
def root_me_sq_error(true,pred):
  temp=mean_sq_err(true,pred)
  return temp**0.5

In [ ]:
root_me_sq_error(true1,pred1)

2.3804761428476167

In [ ]:
test=np.array([[1,2],[3,4]])

In [ ]:
test.flatten()

array([1, 2, 3, 4])

In [ ]:
test

array([[1, 2],
       [3, 4]])