In [1]:
import tensorflow.keras as keras
from tensorflow.keras.layers import *
from tensorflow.keras.models import *
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import *

In [9]:
X = np.random.random((1000,100))
y = np.random.random((1000,10))
y=y/np.sum(y,axis=1).reshape((-1,1))
y = np.argmax(y,axis=1)

In [12]:
from keras.utils import *
#for using one hot encoder


In [13]:
y_ = to_categorical(y, num_classes=10)

In [14]:
y_.shape


(1000, 10)

In [16]:
y_

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [17]:
model = Sequential()
model.add(Dense(256,input_dim=100))
model.add(Dense(128))
model.add(Dense(10))
model.add(Activation('softmax'))

In [18]:
model.compile(loss='categorical_crossentropy',optimizer='sgd',metrics=['accuracy'])

In [19]:
model.fit(X,y_, epochs=100)

Epoch 1/100
32/32 [==============================] - 1s 2ms/step - loss: 2.4174 - accuracy: 0.1098
Epoch 2/100
32/32 [==============================] - 0s 2ms/step - loss: 2.3419 - accuracy: 0.1177
Epoch 3/100
32/32 [==============================] - 0s 1ms/step - loss: 2.3177 - accuracy: 0.1327
Epoch 4/100
32/32 [==============================] - 0s 1ms/step - loss: 2.3016 - accuracy: 0.1409
Epoch 5/100
32/32 [==============================] - 0s 2ms/step - loss: 2.2899 - accuracy: 0.1548
Epoch 6/100
32/32 [==============================] - 0s 1ms/step - loss: 2.2761 - accuracy: 0.1629
Epoch 7/100
32/32 [==============================] - 0s 1ms/step - loss: 2.2829 - accuracy: 0.1738
Epoch 8/100
32/32 [==============================] - 0s 1ms/step - loss: 2.2475 - accuracy: 0.1802
Epoch 9/100
32/32 [==============================] - 0s 2ms/step - loss: 2.2419 - accuracy: 0.1870
Epoch 10/100
32/32 [==============================] - 0s 2ms/step - loss: 2.2239 - accuracy: 0.1746
Epoch 11/

In [20]:
predicted_proba = model.predict(X)
print (predicted_proba)

[[0.02843288 0.06607405 0.05544253 ... 0.05208556 0.01923344 0.24102452]
 [0.03917684 0.10954227 0.0383179  ... 0.07363186 0.22484303 0.08690676]
 [0.26361144 0.02947165 0.02829551 ... 0.03704872 0.08427622 0.03282056]
 ...
 [0.06602997 0.00886693 0.03079349 ... 0.01398163 0.36653078 0.05485282]
 [0.07709374 0.02050386 0.05623129 ... 0.10243903 0.10967172 0.1610924 ]
 [0.3871024  0.00863823 0.12282299 ... 0.02253174 0.02172015 0.11442941]]


In [21]:
predicted_classes = np.argmax(predicted_proba,axis=1)
print (predicted_classes)
print (accuracy_score(y,predicted_classes))

[6 8 4 1 8 9 3 9 4 5 4 9 5 6 9 5 4 4 0 4 3 5 4 4 3 8 9 4 2 1 4 3 1 9 3 0 8
 7 3 4 3 9 2 4 6 6 6 6 6 5 6 6 8 5 3 4 7 4 4 0 4 6 2 5 9 6 3 3 4 0 5 3 8 4
 3 9 4 3 4 7 2 5 7 6 7 1 3 3 2 3 7 6 4 4 8 3 9 3 4 2 3 7 6 4 7 3 4 4 6 7 0
 8 3 6 9 9 3 0 3 9 4 6 1 9 9 5 8 0 3 8 4 9 9 2 4 9 3 2 6 1 5 0 9 5 6 8 3 2
 9 4 0 7 4 1 8 6 4 9 6 6 6 7 4 1 5 6 3 4 6 1 0 7 0 4 6 4 0 4 3 7 7 0 2 5 3
 2 4 6 3 5 4 0 4 4 4 4 4 9 7 5 0 3 0 7 0 2 0 4 0 9 9 9 7 4 4 5 3 4 8 6 0 4
 9 7 9 4 4 4 3 4 6 7 9 0 6 4 9 0 9 6 4 6 6 0 6 6 1 8 6 6 9 7 7 5 4 9 3 4 7
 3 6 6 6 9 8 7 7 4 9 7 9 0 7 8 4 4 4 0 4 0 3 7 3 5 4 5 5 0 8 6 5 3 9 5 9 4
 0 8 0 3 0 8 9 0 0 4 9 9 4 0 1 0 0 4 0 9 9 3 8 0 7 4 6 4 4 6 7 8 4 5 8 9 0
 5 9 4 3 0 6 9 4 7 4 7 1 3 8 4 3 5 1 3 7 5 4 2 6 0 9 9 6 7 0 3 1 1 6 6 8 6
 4 4 5 0 9 7 4 6 7 4 3 3 6 9 0 0 5 6 3 4 2 9 6 5 8 4 4 6 0 6 9 7 5 9 4 6 5
 5 0 8 6 0 6 7 0 8 7 6 3 4 6 0 4 1 8 4 0 4 7 4 5 1 9 5 1 8 2 0 7 9 9 5 6 6
 2 2 0 7 8 9 0 4 4 4 9 0 7 8 8 8 9 0 7 4 0 0 9 0 3 3 7 9 3 9 4 3 7 3 9 6 5
 7 7 4 4 9 7 5 8 4 7 0 7 